#!/bin/bash
# This script is generated to analyse differential gene expression between human peritoneal dialysis effluent cells treated with or without alanyl-glutamine supplemented peritoneal dialysis fluid in a randomized controlled cross-over pilot study
#Source Array express (http://www.ebi.ac.uk/arrayexpress/) 
#ArrayExpressAccession:	E-MTAB-5462
#Generated by Pradeep Ramagiri on 20180313

# Trimming Truseq adapter Index1/18 (GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCACATCTCGTAT) from P1-AG.fastq.gz file and retaining sequences with Phred quality >= 33. 

cd /media/pradeep/NGSPR_HOME/RNASeq-Test_Oxford_PR

do

java -jar /media/pradeep/NGSPR_HOME/RNASeq-Test_Oxford_PR/Trimmomatic-0.36/trimmomatic-0.36.jar SE -phred33 P1.fastq.gz trimmed_P1.fastq.gz ILLUMINACLIP:TruSeq-SE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:20

java -jar /media/pradeep/NGSPR_HOME/RNASeq-Test_Oxford_PR/Trimmomatic-0.36/trimmomatic-0.36.jar SE -phred33 P1-AG.fastq.gz trimmed_P1-AG.fastq.gz ILLUMINACLIP:TruSeq-SE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:20

done
